FROM apache/airflow:2.10.4-python3.11

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        default-jre-headless \
        libffi-dev \
        libkrb5-dev \
        libsasl2-dev \
        libsasl2-modules-gssapi-mit \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark \
    apache-airflow-providers-http \
    dbt-core \
    dbt-spark \
    pyspark==3.3.0 \
    pyhive \
    requests \
    thrift \
    thrift-sasl
